apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: users-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-app
  template:
    metadata:
      labels:
        app: users-app
    spec:
      containers:
      - name: users-app
        image: 192.168.0.8:5000/users-service:latest
        ports:
        - containerPort: 50001
        imagePullPolicy: Always
