apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: catalog-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-app
  template:
    metadata:
      labels:
        app: catalog-app
    spec:
      containers:
      - name: catalog-app
        image: 192.168.0.8:5000/catalogs-service:2.0
        ports:
        - containerPort: 50003
        imagePullPolicy: Always
